package tech.simter.file.core

import java.nio.file.Path
import java.time.OffsetDateTime
import java.util.*

/**
 * The file path generator.
 *
 * @author RJ
 */
@FunctionalInterface
interface FilePathGenerator {
  /**
   * Generate a file path within the [ts] and [uuid] context.
   *
   * If the return value is not a absolute path, means it is a path relative to the basePath.
   * Whether resolve to a absolute path dependents on the implementation.
   * If resolve to a absolute path, you should make sure the application has
   * the right permission to access it.
   *
   * @param[describer] the file describer
   * @param[ts] the timestamp when the caller call this method
   * @param[uuid] the unique id generated by the caller
   */
  fun resolve(
    describer: FileDescriber,
    ts: Optional<OffsetDateTime> = Optional.empty(),
    uuid: Optional<UUID> = Optional.empty()
  ): Path
}
